# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self,system):
        self.system=system

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.iteratioLabel = QtWidgets.QLabel(Dialog)
        self.iteratioLabel.setObjectName("iteratioLabel")
        self.verticalLayout.addWidget(self.iteratioLabel)

        self.iterationCount = QtWidgets.QSpinBox(Dialog)
        self.iterationCount.setMaximum(999999999)
        self.iterationCount.setValue(self.system.maxIteration)
        self.iterationCount.setObjectName("iterationCount")
        self.verticalLayout.addWidget(self.iterationCount)
        

        self.errorLabel = QtWidgets.QLabel(Dialog)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)

        self.errorCount = QtWidgets.QDoubleSpinBox(Dialog)
        self.errorCount.setDecimals(1)
        self.errorCount.setSingleStep(0.1)
        self.errorCount.setObjectName("errorCount")
        self.errorCount.setValue(self.system.currError)
        self.verticalLayout.addWidget(self.errorCount)

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.buttonBox.clicked.connect(self.actionOnClick)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.iteratioLabel.setText(_translate("Dialog", "Ilość iteracji:"))
        self.errorLabel.setText(_translate("Dialog", "Wartość błędu:"))

    def actionOnClick(self):
        self.system.currError=self.errorCount.value()
        self.system.maxIteration=self.iterationCount.value()
        

    
    
